
 POST http://localhost:5000/posts
 Content-Type: application/json

{
    "title": "Testing on REST again", "message": "Fuck you", "creator": "Deex", "tags", "Bitch, hello, fuck"

}

###
GET http://localhost:5000/posts